#!bash

echo "Setting CONFLUENT_CLOUD_BOOTSTRAP_SERVER"
export CONFLUENT_CLOUD_BOOTSTRAP_SERVER="pkc-ymrq7.us-east-2.aws.confluent.cloud:9092"
echo "Setting CONFLUENT_CLOUD_API_KEY"
export CONFLUENT_CLOUD_API_KEY="ZUILJIQEJDY2VG6P"
echo "Setting CONFLUENT_CLOUD_API_SECRET"
export CONFLUENT_CLOUD_API_SECRET="lMTQYdnpM+igdgTAJCj3dYhyQYpOpcxwEzIj2ahCbTyl7iQi+3eWUZS5RubgImn5"